Filter generated webp files only
plan2net/webp pull request #86
Opened 2023-07-06 10:35 UTC by kauz56

This changes the filtering behaviour for file lists, so that it only filters generated webp files, but not regular, user submitted ones. These are distinguished by checking for a preceding file suffix before the ".webp".

2023-07-07 21:04 UTC, xerc requested changes
`1 === \preg_match('/[^.]\.[^.]+?\.webp$/', $itemIdentifier)`

2023-07-07 21:04 UTC, xerc commented on Classes/Core/Filter/FileNameFilter.php
> +        if (preg_match('/\.[^\.]*\.webp$/', $itemIdentifier) === 1) {
fyi/ @kauz56 ; this detects empty previous extension FE; `..webp`

2023-07-10 11:39 UTC, xerc requested changes
there will no generated file with `.WHATEVERwebp$`

2023-07-10 11:47 UTC, kauz56 commented
@xerc I'm sorry, I don't understand what you mean. Can you be more specific?

2023-07-10 12:01 UTC, xerc commented
`/\.[^\.]+\..*webp$` filters for expl. `.x.xwebp` which can not happen => just copy my [statement](https://github.com/plan2net/webp/pull/86#pullrequestreview-1519805319)

2023-07-10 12:33 UTC, kauz56 commented
@xerc So you're saying my regex would match a file ".something.webp", whereas your's wouldn't? If so, I don't see any added value there, because the file list filters dotfiles by default. If it didn't filter dotfiles by default, a scenario where someone uploads a file `.jpg` would be possible. Resulting, the generation of a file `.jpg.webp` would also be possible, which my regex would then filter out correctly.

Feel free to correct me if I'm missing the point, but I don't think statements like "just copy my code" are very productive. If I'm asked to consider a change, I need to understand what I'd be changing and why.

2023-07-10 12:43 UTC, xerc commented
your new regex matches `fefewf.fcew.cefewebp` which can not happen

2023-07-10 13:17 UTC, kauz56 commented
@xerc Thanks for clarifying! I changed the commit accordingly.

2023-07-10 13:37 UTC, xerc commented
np // please run `php .Build/bin/php-cs-fixer fix --config php-cs-fixer.config.php` & include the modif./cleanup
and consider the `\` ref. https://github.com/plan2net/webp/blame/master/Classes/Converter/PhpGdConverter.php#L66

2023-07-10 14:07 UTC, kauz56 commented
Done. @maintainers If you decide to merge this, please consider squashing the commits.

2023-07-10 14:12 UTC, xerc approved these changes

2023-07-11 08:29 UTC, wazum commented
@kauz56  Thanks, I solved this a little different, Commit 3b4f0715a0a6fe9f8bf24af8617fc5c99144009d in master (let me know if that works for you, then I'll tag it):
I introduced a new extension configuration for the pattern to exclude (with a default pattern), so it's now totally flexible.

2023-07-11 09:17 UTC, kauz56 commented
@wazum Works for me, thanks!

2023-07-26 20:32 UTC, kauz56 commented
Closing, solved by https://github.com/plan2net/webp/commit/3b4f0715a0a6fe9f8bf24af8617fc5c99144009d.

2023-07-26 20:32 UTC, closed without merging